Single mode and Multi-mode remediation framework deployment/decommission script refinements
Cloudneeti/aws-auto-remediation pull request #7
Opened 2020-02-17 07:04 UTC by Bhushanb333

2020-02-18 05:28 UTC, rahulkhengare requested changes
Remove AWS from stack and resource names

2020-02-18 06:22 UTC, Bhushanb333 commented
> Remove AWS from stack and resource names

Updated required prefix for stack and resources

2020-02-18 09:14 UTC, ankitsrao approved these changes

2020-02-20 11:09 UTC, rahulkhengare approved these changes

2020-02-20 11:09 UTC, merged